Storybook
LaunchUpCorp/Dashboard-Builder pull request #1
Opened 2023-04-26 18:23 UTC by kelvin3127

Added storybook to the application

2023-04-26 19:21 UTC, YoussefLaunchUp requested changes
Make sure to assign yourself to the PR,
Add Reviewers (namely Myself, Mike and the rest of the group)
Do not make PRs against main, PRs are to be merging into dev not main.
Make sure that only the files that need to be added into the repo are added.

2023-04-27 01:59 UTC, YoussefLaunchUp requested changes
Documentation for How to use Storybook (both how to get it up and running as well as how to add new stories is needed)

2023-04-27 01:59 UTC, YoussefLaunchUp commented on frontend/src/stories/Button.stories.ts
This entire stories folder needs to be removed

2023-04-27 01:59 UTC, YoussefLaunchUp commented on frontend/src/stories/assets/code-brackets.svg
This entire assets folder needs to be removed

2023-04-27 18:54 UTC, kelvin3127 commented on frontend/src/stories/Button.stories.ts
> Documentation for How to use Storybook (both how to get it up and running as well as how to add new stories is needed)

Removed Stories Folder and added a Storybook Readme MD File

2023-04-27 22:24 UTC, roxanehe commented
Thanks Kelvin!!

2023-04-29 15:42 UTC, YoussefLaunchUp requested changes
PR looks good, small nit added.

Also the pr title is wrong, it needs to follow conventional commits semantics.

2023-04-29 15:42 UTC, YoussefLaunchUp commented on frontend/src/Stores/counter.ts
Stores folder should be lowercase.

2023-04-29 17:09 UTC, YoussefLaunchUp approved these changes

2023-04-29 17:10 UTC, merged

2023-05-01 16:02 UTC, neli-rashkova reviewed
Looks great, thanks Kelvin!