Feat: Added Dropdown Component
LaunchUpCorp/Dashboard-Builder pull request #7
Opened 2023-05-08 04:00 UTC by kelvin3127

Dropdown Component

- [x] New Feature

### Description
A dropdown component that takes in data to make a select dropdown.
Includes props for styling
Includes Storybook

### Testing Instructions Component

Open terminal and run "npm run dev"
Open application in browser with local host.
Import dropdown component and add to the template.
Dropdown component Props include:                                                             Example   <Dropdown
            msg - Changes the initial select message for dropdown.                                           msg ="Select"
            text - Changes the color of the text for dropdown.                                                    text = "text-white"
            hover - Changes the background color when hovered over dropdown.                   hover = "hover:bg-blue-700"
            color - Changes the background color of the dropdown.                                          color = "bg-blue-500"
            size - Changes the width size of the dropdown.                                                         size = "w-1/3"
            selOptions - This is the data of the dropdown.                                                           :selOptions =  arr1
If no props are included the component will have it's own default props.                        />

### Testing Instructions Storybook

Open terminal and run "npm run storybook"
Open storybook in browser "http://localhost:6006/", there will be 5 styles on the side where you can choose from. Each style can update the Initial dropdown select message and text color between black or white as well as size.

### Screenshots
Dropdown Component
![3](https://user-images.githubusercontent.com/46061373/236730909-30bba6a6-adf2-40d4-bf51-874d627b7f5e.PNG)

Storybook
Orange Style with Black Text
![1](https://user-images.githubusercontent.com/46061373/236729063-fc8abe24-616a-4120-9c81-1b591837b741.PNG)

Blue Style with White Text
![2](https://user-images.githubusercontent.com/46061373/236729222-87c4a631-cf51-49b4-8ddc-9df3c6f14d44.PNG)

2023-05-08 22:27 UTC, roxanehe commented
looks nice! well done

2023-05-09 21:24 UTC, YoussefLaunchUp requested changes
The Drop down should be able to take any type of component as a child not just text through the prop array. 

![image](https://github.com/LaunchUpCorp/Dashboard-Builder/assets/104530466/6c46e58a-a48b-4514-9f03-4636914bca6c)




![image](https://github.com/LaunchUpCorp/Dashboard-Builder/assets/104530466/806141e0-73ea-4868-b766-5e3ebd1ecaf1)


You can use this as reference: https://bootstrap-vue.org/docs/components/dropdown

2023-05-09 21:24 UTC, YoussefLaunchUp commented on frontend/src/App.vue
This should not be in App.vue Return the file to what it was like before

2023-05-10 18:35 UTC, kelvin3127 commented on frontend/src/App.vue
Made necessary changes

2023-05-10 18:35 UTC, kelvin3127 commented
> The Drop down should be able to take any type of component as a child not just text through the prop array.
> 
> ![image](https://user-images.githubusercontent.com/104530466/237223789-6c46e58a-a48b-4514-9f03-4636914bca6c.png)
> 
> ![image](https://user-images.githubusercontent.com/104530466/237223293-806141e0-73ea-4868-b766-5e3ebd1ecaf1.png)
> 
> You can use this as reference: https://bootstrap-vue.org/docs/components/dropdown

Update code to fit the requirments

2023-05-15 16:09 UTC, YoussefLaunchUp approved these changes

2023-05-15 20:52 UTC, roxanehe approved these changes
good work!

2023-05-15 21:26 UTC, merged