feat: Upload csv file
LaunchUpCorp/Dashboard-Builder pull request #9
Opened 2023-05-10 18:50 UTC by kelvin3127

### Description
A component to upload csv files into the application.

### Testing Instructions

Please provide step-by-step instructions for how to manually test the changes. Be sure to include any relevant URLs, input data, or other information necessary for testing.

### Screenshots

If applicable, add screenshots to help explain your changes. This can be particularly helpful for frontend and design-related changes. Please provide screenshots for different devices and screen sizes (Mobile, Tablet, and Desktop) if possible.

2023-05-15 16:54 UTC, YoussefLaunchUp requested changes
make sure to fix eslint issues as well

2023-05-15 16:54 UTC, YoussefLaunchUp commented on frontend/src/components/Upload/Upload.vue
Should be renamed to index.vue

2023-05-15 21:49 UTC, kelvin3127 commented on frontend/src/components/Upload/Upload.vue
Renamed and fixed eslint

2023-05-17 02:22 UTC, YoussefLaunchUp approved these changes
Good work

2023-05-17 14:21 UTC, roxanehe approved these changes
great work

2023-05-17 17:18 UTC, neli-rashkova approved these changes
Great work

2023-05-17 22:15 UTC, merged